program = expression* ;

expression = varDecl ;

varDecl = "let" IDENT ":" TYPE "=" expression
        | term ;
term    = factor ( ( "-" | "+" ) factor )* ;
factor  = unary ( ( "/" | "*" ) unary )* ;
unary   = ( "-" ) unary 
        | primary ;
primary = NUMBER | "(" expression ")" ;