program = expression* ;

expression = if ;

if = "if" expression expression* (("else if" expression expression*)*? "else" expression*)? "end"
   | varDecl ;

varDecl = "let" IDENT ":" TYPE "=" expression
        | equality ;
equality = comparison ( ( "!=" | "==" ) comparison )* ;
comparison = term ( ( | "<" | ">" | "<=" | ">=") term)*;
term    = factor ( ( "-" | "+" ) factor )* ;
factor  = unary ( ( "/" | "*" ) unary )* ;
unary   = ( "-" | "!") unary 
        | primary ;
primary = NUMBER | "(" expression ")" ;